### ISSUE TITLE
Edit Container - Updating Fields Removes Description

### ISSUE THREAD

**Issue by matthewstewart** [biobricks/bionet-new#102]
When editing a container and after entering text in the description field:
  1. If the Rows, Columns, or Grid Lines fields are changed, the text in the description field is removed.
  2. If the Name or View fields are changed, the text in the description field remains.
![editcontainerdescdrop1](https://user-images.githubusercontent.com/7444927/44415606-c1499c80-a525-11e8-9b59-81c95072d817.png)
![editcontainerdescdrop2](https://user-images.githubusercontent.com/7444927/44415617-c575ba00-a525-11e8-81d6-198843a80661.png)

**Comment by autonomous1** [comment]
I cannot reproduce this issue.

**Comment by matthewstewart** [comment]
I could not reproduce the error when trying  several days later.
