### ISSUE TITLE
Page needs to be refreshed after disconnecting from session

### ISSUE THREAD

**Issue by autonomous1** [biobricks/bionet-new#11]
When attempting to re-establish connection to the server after disconnecting (ie. resuming session after computer is put to sleep), the page needs to be refreshed. Logging out and back in does not work. Here is a console log obtained from the aforementioned scenario:

attempting to connect
bundle.js:80340 connecting to websocket wss://endylab.stanford.edu
bundle.js:80003 Not logged in
app.state.global.user
Object {userData: Object, token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6InRzY…TMyfQ.E85IQfIbkBdd3FjuiKT-lV-YcHcobkLoSeMxIyFTEaY"}

**Comment by Juul** [comment]
I've tested this repeatedly and could not replicate. I've added proper heartbeat and improved the disconnect detection. I also verified that the authentication token generated by the login system is valid for two weeks. Let me know if this is still an issue, if not then I let's try to troubleshoot when we're sitting next to each other.

**Comment by Juul** [comment]
Let me know if this still happens

**Comment by Juul** [comment]
I believe this to be fixed. Please re-open if it re-occurs.

**Comment by Juul** [comment]
If this shows up again we should look at [this nginx module](https://github.com/yaoweibin/nginx_tcp_proxy_module).
