### ISSUE TITLE
Lab Profile - Map Grid Layout Break

### ISSUE THREAD

**Issue by matthewstewart** [biobricks/bionet-new#111]
The cells in the map do not position correctly in the grid.
![labprofile1](https://user-images.githubusercontent.com/7444927/44426010-64101400-a542-11e8-8cd4-1c2779e7d38a.png)

**Comment by autonomous1** [comment]
This issue is specific to google chrome browser.

**Comment by matthewstewart** [comment]
Moving To CSS Grid Solution.
