### ISSUE TITLE
Container Profile / Physical Profile - Clicking Favorite Button Breaks Layout

### ISSUE THREAD

**Issue by matthewstewart** [biobricks/bionet-new#114]
When in a container profile, clicking the favorite button makes the profile disappear:
![containerfavorite1](https://user-images.githubusercontent.com/7444927/44432695-fb339680-a557-11e8-89ea-898809947e81.png)
![containerfavorite2](https://user-images.githubusercontent.com/7444927/44432727-228a6380-a558-11e8-95b1-12fd4fff8463.png)

**Comment by autonomous1** [comment]
The favorites button currently toggles the display of favorites on/off. Please provide details on the ui to show/hide/add/remove favorites.

**Comment by matthewstewart** [comment]
Adding and removing the favorites is the toggle button.
The favorites UI we is in the demo directory:
https://github.com/biobricks/bionet-new/blob/master/src/js/components/demo/Favorites.js

**Comment by matthewstewart** [comment]
It can be viewed at /ui/favorites within the application.
