### ISSUE TITLE
Container Profile - Map Panel Nav To Physical Broken

### ISSUE THREAD

**Issue by matthewstewart** [biobricks/bionet-new#115]
When viewing a container profile and clicking on a child physical in the profile list, the physical profile loads correctly. When clicking on a child physical in the map panel grid, the layout breaks and the physical profile does not load. Trying to refresh the page results in the whole page going blank and errors in the console.

![containerprofilemapnav1](https://user-images.githubusercontent.com/7444927/44433365-d260d080-a55a-11e8-889c-6ff03c10f4d3.png)
![containerprofilemapnav2](https://user-images.githubusercontent.com/7444927/44433366-d4c32a80-a55a-11e8-8a26-bee2175a356c.png)
![containerprofilemapnav3](https://user-images.githubusercontent.com/7444927/44433371-d7258480-a55a-11e8-95f4-c63225e9144d.png)
![containerprofilemapnav4](https://user-images.githubusercontent.com/7444927/44433375-d8ef4800-a55a-11e8-9a3c-54366e14987e.png)

**Comment by autonomous1** [comment]
Cannot reproduce this issue. Will leave open until more details on how to reproduce this issue are provided.

**Comment by matthewstewart** [comment]
### Explanation
The errors indicate that the render failed trying to reference an attribute of an undefined object.
This indicates that the render is being attempted on an object without first checking the object is loaded.

#### Example A - Without Checking (produces above error)
item has not loaded yet so it will error on traversing the object
```
render() {
  return(
    <span>{item.name}</span>
  );
}
```

#### Example B - With Checking (prevents above error)
If item has not yet loaded, it will return false before passing the '&&'. False in react/preact does not render.
```
render() {
  return(
    <span>{item && Object.keys(item).length > 0 && item.name}</span>
  );
}
```

#### Example C - Render Ternary (prevents above error)
```
render() {
  return(
    <div>
      {(item && Object.keys(item).length > 0) ? (
        <span>{item.name}</span>
      ) : null }
    </div>
  );
}
```
