### ISSUE TITLE
Incorrect login prevents sign up

### ISSUE THREAD

**Issue by Koeng101** [biobricks/bionet-new#166]
![2018-09-28-105530_1920x1080_scrot](https://user-images.githubusercontent.com/2896607/46225081-09ba5e00-c30d-11e8-9aaa-a2d54d99fa6e.png)

If you try to login with an old account and fail, "Incorrect username or password." blocks you from the sign up button.

**Comment by matthewstewart** [comment]
Fixed.
commit 48193a9f0c2fb989164253708c6901229001a0fb
