### ISSUE TITLE
Signup page confusion

### ISSUE THREAD

**Issue by Koeng101** [biobricks/bionet-new#167]
Tried to get a few folks to signup - there was consistent confusion on the signup page between 'Password' and 'New Account Password'.

If the wording can be changed to 'Your Password', I think that would relieve the confusion.

**Comment by matthewstewart** [comment]
Misunderstanding.  The input label was the issue.

**Comment by matthewstewart** [comment]
Label Changed To 'Your Password'.
commit 0eda3249c4e57619c6d9d012d6ba0448aa985877
