### ISSUE TITLE
Clicking pencil on inventory page leads to duplication of all buttons on left side

### ISSUE THREAD

**Issue by akshaywari** [biobricks/bionet-new#32]
1. Go to inventory page
2. Click pencil button
3. Only thing that happens is the side bar duplicating each time the button is pressed.

**Comment by autonomous1** [comment]
Can't reproduce - can you check your console log to see if there are any errors and paste stack trace in comment?

**Comment by autonomous1** [comment]
It may have been fixed in another related issue - closing since it cannot be duplicated at this time.
