### ISSUE TITLE
Inventory page doesn't load on first click

### ISSUE THREAD

**Issue by akshaywari** [biobricks/bionet-new#33]
Using chrome, the inventory page doesn't load when I click the top bar button from a different page. I need to refresh the page manually for the page to load.

**Comment by Juul** [comment]
Thank you for the report! We are having trouble replicating this bug. Could you give tell me the version of chrome and the operating system?

**Comment by autonomous1** [comment]
I was able to replicate this bug. Turns out ashnagz changeState does not trigger re-rendering when invoking app.changeState whereas app.setState updates correctly. So I switched to setState to fix this issue, however the problem remains with changeState.
