### ISSUE TITLE
Unable to run BLAST search

### ISSUE THREAD

**Issue by ccmeyer** [biobricks/bionet-new#41]
Tried entering in a local BLAST search on the for a sequence that matches one of the plasmids that I entered and it returns:
"Search failed: Error: BLAST Database error: No alias or index file found for nucleotide database [main-1] in search path [/home/bionet/bionet/blast::]"
Then a global search just returns no results

**Comment by Juul** [comment]
Thanks! Looks like it might be caused by difference in the BLAST version.
