### ISSUE TITLE
Random deletion of benches

### ISSUE THREAD

**Issue by ccmeyer** [biobricks/bionet-new#46]
While Drew and I were trying to create some benches and drawers within those benches, the entire benches container disappeared along with its contents. I think that they are saved somewhere because when I tried to create objects with the same name it would throw and error and not let me make it. Unfortunately I am not really sure what caused it to happen but it has happened to me twice where I clicked somewhere outside of the benches container and then it disappeared.

**Comment by Juul** [comment]
If this is repeatable can you outline the steps to make it happen? Also, could you give me the approximate name of one of the disappeared containers so I can look for it in the database?

**Comment by Juul** [comment]
Ping @ccmeyer can you tell me the name of one of the disappeared containers?

**Comment by matthewstewart** [comment]
Inventory Refactor - commit 22f009c43fdc6dc3a8053991d5fc18a1e64e6ac2
