### ISSUE TITLE
Add missing fields when creating new virtal+physicals in inventory

### ISSUE THREAD

**Issue by Juul** [biobricks/bionet-new#49]
Fields:

* Description `.description`
* Provenance `.provenance`
* Terms and conditions `.terms`

**Comment by Juul** [comment]
See `edit virtual` for example.

**Comment by autonomous1** [comment]
These attributes have been added to the create virtual/physical instances form. It may be a good idea to sync these attributes with the search result virtual form.

**Comment by Juul** [comment]
Yeah I already added them there :) that's why I said:

> See `edit_virtal` for example.
