### ISSUE TITLE
bionet icon (now in the right place!)

### ISSUE THREAD

**Issue by eyesmo** [biobricks/bionet-new#56]
My cursor indicates the bionet icon in the top right corner is a hyperlink/is clickable, but nothing happens when I click it, and right clicking indicates that it's just an image.

<img width="459" alt="bionetbug" src="https://user-images.githubusercontent.com/2289040/37692234-59f30b3e-2c85-11e8-8bed-2518d1431c6e.png">
<img width="491" alt="screen shot 2018-03-20 at 4 55 24 pm" src="https://user-images.githubusercontent.com/2289040/37692236-5db2bae4-2c85-11e8-8cad-51f393eb47de.png">

**Comment by Juul** [comment]
Thanks! Fixed the link to point to the main page of the app and deployed
