### ISSUE TITLE
Empty Search Bar Weirdness

### ISSUE THREAD

**Issue by eyesmo** [biobricks/bionet-new#58]
If I haven't typed anything into the search bar, and hit search, nothing happens. However, if I have a couple of characters (say, 'gf') typed into the search bar, but then I delete them, and then hit search, the last character I deleted ('g') appears in the search bar, and the page returns results for that character.

On a fresh page, before I've typed anything:
<img width="1114" alt="screen shot 2018-03-20 at 9 40 43 pm" src="https://user-images.githubusercontent.com/2289040/37692595-abefbcbe-2c87-11e8-8713-c66af1427a08.png">

After clicking search without typing anything:
<img width="1092" alt="screen shot 2018-03-20 at 9 41 11 pm" src="https://user-images.githubusercontent.com/2289040/37692605-c495968a-2c87-11e8-8251-e8b16f313765.png">

I enter a couple of random characters:
<img width="1034" alt="screen shot 2018-03-20 at 9 41 26 pm" src="https://user-images.githubusercontent.com/2289040/37692625-e2f3afb8-2c87-11e8-918d-f4231da26008.png">

I then delete the random characters:
<img width="1033" alt="screen shot 2018-03-20 at 9 41 43 pm" src="https://user-images.githubusercontent.com/2289040/37692633-f12e8fbc-2c87-11e8-95d6-d8337ee01e1a.png">

And finally, I click search again:
<img width="996" alt="screen shot 2018-03-20 at 9 41 53 pm" src="https://user-images.githubusercontent.com/2289040/37692637-fcd747dc-2c87-11e8-9384-7de6eebaf1ac.png">

**Comment by Juul** [comment]
Thank you for surfacing these issues! This is very useful for us!

**Comment by matthewstewart** [comment]
Inventory Refactor - commit 22f009c43fdc6dc3a8053991d5fc18a1e64e6ac2
