### ISSUE TITLE
Bug when clicking a physical instance from a virtual

### ISSUE THREAD

**Issue by Juul** [biobricks/bionet-new#70]
This is replicable on endylab for the virtual `pE-FLP`

Clicking the instance takes you to:

https://endylab.stanford.edu/virtual/show/v-7dffc9fe-ca2d-4b59-a04f-58e645f754ec

**Comment by autonomous1** [comment]
Adding Marc since this issue is caused by a null value being returned from the level-tree-index path method, for which there would normally be a valid path returned. It is possibly related to deletion of containers without also deleting the contents, leaving orphaned items in inventory.

**Comment by Juul** [comment]
fixed
