### ISSUE TITLE
delete physical messes up inventory tree

### ISSUE THREAD

**Issue by Juul** [biobricks/bionet-new#8]
Tim says:
> on my local bionet node, delete physical causes the root inventory item to be set to the id of the physical that was just deleted, then when navigating anywhere an error message is displayed in the console, key not found in database

**Comment by Juul** [comment]
Found and fixed bugs in [level-tree-index](https://github.com/biobricks/level-tree-index). Also added more unit tests and further improvements to prevent race conditions. Let me know if this is still an issue.

**Comment by Juul** [comment]
@autonomous1 can you confirm whether this is fixed?

**Comment by Juul** [comment]
@autonomous1 ping

**Comment by Juul** [comment]
I believe this to be fixed. Please re-open if it re-occurs.

**Comment by matthewstewart** [comment]
Inventory Refactor - commit 22f009c43fdc6dc3a8053991d5fc18a1e64e6ac2
