### ISSUE TITLE
Map Renders Outside Parameters

### ISSUE THREAD

**Issue by matthewstewart** [biobricks/bionet-new#82]
The map in the screenshot below is set to 3 columns and 6 rows. When rendering, the grid lines extend slightly (3 pixels or so) beyond that on the right and the bottom, making it look like there are additional grid cells that are beyond view:
![maprender](https://user-images.githubusercontent.com/7444927/44301858-222d6680-a2d3-11e8-962b-b43d1f94ffbf.png)

**Comment by autonomous1** [comment]
This issue is specific to google chrome and related to #111

**Comment by autonomous1** [comment]
Problem is that there is no work-around for the linear-gradient issue with chrome so maybe switching to css grid would be the solution..

**Comment by matthewstewart** [comment]
We have one that is a work in progress:
https://github.com/biobricks/bionet-new/blob/master/src/js/components/demo/MapGrid.js

**Comment by matthewstewart** [comment]
Inventory Refactor - commit 22f009c43fdc6dc3a8053991d5fc18a1e64e6ac2
