### ISSUE TITLE
Lab Editor New Container Form - Font Size / Width / Height 

### ISSUE THREAD

**Issue by matthewstewart** [biobricks/bionet-new#91]
While creating a new container within the lab editor:
1. The font-size input does not change the font-size.
2. The width and height inputs in the new item form represent row span and column span within the parent container, no inputs are present for the items rows and columns.
3. When the new container is saved, it adopts the rows and columns from the lab and you have to re-edit the rows and columns within the 2 panel layout.
![labeditorfontsize](https://user-images.githubusercontent.com/7444927/44303657-47ce6600-a2fb-11e8-9893-35982828cf9e.png)

**Comment by autonomous1** [comment]
Added rows, columns to form. The font size is updated after the item is saved but not when form values changed.

**Comment by matthewstewart** [comment]
The step attribute needs to be present also to avoid float input.
```
<input type="number" min="1" max="100" step="1" />
```
